[usecli]
command_name = "usecli"
title = "usecli"
title_file = ""
title_font = "ansi_shadow"
description = "A custom CLI tool"
commands_dir = "cli/commands/custom"
templates_dir = "cli/templates"
themes_dir = "cli/themes"
theme = "default"
hide_init = false
hide_inspire = false
hide_make_command = false
hide_make_theme = false
