[colors]
# Core semantic colors
primary = "#8caaee"
secondary = "#a6d189"
accent = "#ef9f76"

success = "#a6d189" # Green
error = "#e78284"   # Red
warning = "#e5c890" # Yellow
info = "#99d1db"    # Teal / Blue

# Text
foreground = "#c6d0f5"       # Text
foreground_muted = "#b5bfe2" # Subtext

# Surfaces
background = "#303446"   # Base
border = "#51576d"       # Surface
border_focus = "#babbf1" # Focus Ring

# UI semantics
command = "#8caaee"
option = "#8caaee"
link = "#8caaee"
prompt = "#a6d189"

panel_primary = "#a6d189"
panel_secondary = "#8caaee"
panel_accent = "#ef9f76"
