[colors]
# Core semantic colors
primary = "#8aadf4"
secondary = "#a6da95"
accent = "#f5a97f"

success = "#a6da95" # Green
error = "#ed8796"   # Red
warning = "#eed49f" # Yellow
info = "#91d7e3"    # Teal / Blue

# Text
foreground = "#cad3f5"       # Text
foreground_muted = "#b8c0e0" # Subtext

# Surfaces
background = "#24273a"   # Base
border = "#494d64"       # Surface 
border_focus = "#b7bdf8" # Focus Ring

# UI semantics
command = "#8aadf4"
option = "#8aadf4"
link = "#8aadf4"
prompt = "#a6da95"

panel_primary = "#a6da95"
panel_secondary = "#8aadf4"
panel_accent = "#f5a97f"
