[colors]
primary = "#8caaee"
secondary = "#a6d189"
accent = "#ef9f76"
success = "#a6d189"
error = "#e78284"
warning = "#e5c890"
info = "#99d1db"
foreground = "#c6d0f5"
foreground_muted = "#b5bfe2"
background = "#303446"
border = "#51576d"
border_focus = "#babbf1"
command = "#8caaee"
option = "#8caaee"
link = "#8caaee"
prompt = "#a6d189"
panel_primary = "#a6d189"
panel_secondary = "#8caaee"
panel_accent = "#ef9f76"
