[colors]
# Core semantic colors
primary = "#8caaee"
secondary = "#babbf1"
accent = "#ca9ee6"

success = "#a6d189" # Green
error = "#e78284"   # Red
warning = "#e5c890" # Yellow
info = "#81c8be"    # Teal / Blue

# Text
foreground = "#c6d0f5"       # Text
foreground_muted = "#a5adce" # Subtext

# Surfaces
background = "#303446"   # Base
border = "#414559"       # Surface 
border_focus = "#babbf1" # Focus Ring

# UI semantics
command = "#8caaee"
option = "#babbf1"
link = "#8caaee"
prompt = "#a6d189"

panel_primary = "#8caaee"
panel_secondary = "#ca9ee6"
panel_accent = "#ef9f76"
