[colors]
primary = "#1e66f5"
secondary = "#40a02b"
accent = "#fe640b"
success = "#40a02b"
error = "#d20f39"
warning = "#df8e1d"
info = "#04a5e5"
foreground = "#4c4f69"
foreground_muted = "#5c5f77"
background = "#eff1f5"
border = "#bcc0cc"
border_focus = "#7287fd"
command = "#1e66f5"
option = "#1e66f5"
link = "#1e66f5"
prompt = "#40a02b"
panel_primary = "#40a02b"
panel_secondary = "#1e66f5"
panel_accent = "#fe640b"
