[colors]
primary = "#60D7FF"
secondary = "#5EFF87"
accent = "#F5FE53"
success = "#5EFF87"
error = "#FE686B"
warning = "#F5FE53"
info = "#60D7FF"
foreground = "#FFFFFF"
foreground_muted = "#BBBBBB"
background = "#000000"
border = "#60D7FF"
border_focus = "#5EFF87"
command = "#60D7FF"
option = "#60D7FF"
link = "#60D7FF"
prompt = "#5EFF87"
panel_primary = "#5EFF87"
panel_secondary = "#60D7FF"
panel_accent = "#F5FE53"

[ansi]
primary = "38;2;96;215;255"
secondary = "38;2;94;255;135"
accent = "38;2;216;176;0"
foreground = "38;2;255;255;255"
foreground_muted = "38;2;158;158;158"
reset = "0"
red = "31"
green = "32"
yellow = "33"
blue = "34"
