[colors]
primary = "#83a598"
secondary = "#b8bb26"
accent = "#fabd2f"

success = "#b8bb26"
error = "#fb4934"
warning = "#fabd2f"
info = "#83a598"

foreground = "#ebdbb2"
foreground_muted = "#a89984"

background = "#282828"
border = "#3c3836"
border_focus = "#b8bb26"

command = "#83a598"
option = "#83a598"
link = "#83a598"
prompt = "#b8bb26"

panel_primary = "#b8bb26"
panel_secondary = "#83a598"
panel_accent = "#fabd2f"
