[colors]
# Core semantic colors
primary = "#83a598"
secondary = "#b8bb26"
accent = "#fabd2f"

success = "#b8bb26" # Green
error = "#fb4934"   # Red
warning = "#fabd2f" # Yellow
info = "#83a598"    # Teal / Blue

# Text
foreground = "#ebdbb2"       # Text
foreground_muted = "#a89984" # Subtext

# Surfaces
background = "#282828"   # Base
border = "#3c3836"       # Surface
border_focus = "#b8bb26" # Focus Ring

# UI semantics
command = "#83a598"
option = "#83a598"
link = "#83a598"
prompt = "#b8bb26"

panel_primary = "#b8bb26"
panel_secondary = "#83a598"
panel_accent = "#fabd2f"
